#!/usr/bin/env python3
"""graphify-setup.py - stand up the CODE knowledge graph and join it to the docs graph.

WHAT THIS IS
  Graphify (graphify.com, Apache 2.0, PyPI `graphifyy`) builds an on-device knowledge graph
  of a codebase that an AI assistant queries instead of grepping, with file:line citations and
  a provenance tag on every edge. This script wires it into an AI-Forward repo and - the part
  that does not exist anywhere else - JOINS it to the pack's documentation graph.

  A repository has two knowledge graphs and the expensive defects live in the gap between them:
    * the DOCS graph (docs-index.js, from V2 frontmatter) holds INTENT
    * the CODE graph (graphify-out/graph.json)          holds REALITY
  Nothing normally traverses both, which is exactly why documentation drifts from code. --join
  computes the two gaps that matter: documentation with no implementation, and risk with no
  governance.

DESIGN RULES THIS HONORS  (knowledge/code-knowledge-graph.md, GK1-GK16)
  * The docs graph stays the record; the code graph is a derived build output (GK2-GK3).
  * Graph the SOURCE, never its generated projections (GK4) - .graphifyignore does this.
  * Provenance is carried through: EXTRACTED -> Verified, INFERRED -> Inferred,
    AMBIGUOUS -> Flagged (GK6). A citation is not a promotion.
  * The join is a LENS: derived, never authoritative, and a prompt rather than a gate (GK11).

USAGE
  graphify-setup.py --check                # is graphify installed, built, ignored, joined?
  graphify-setup.py --install              # uv tool install graphifyy + register the skill
  graphify-setup.py --init                 # write .graphifyignore + .gitignore rules
  graphify-setup.py --build                # full, ignore-respecting re-extraction
  graphify-setup.py --join                 # write docs/lenses/code-doc-join.md
  ... --root <repo> --platform claude,copilot --dry-run --json

Stdlib only. Python 3.8+. Exit 0 on success, 1 on error, 2 on --check findings.
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import shutil
import subprocess
import sys
from collections import Counter, defaultdict

# Windows consoles default to cp1252, which cannot encode the glyphs this tool prints
# (DC-211/PLAT-A). Without this the script dies with UnicodeEncodeError on output alone.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except (ValueError, OSError):
            pass

GRAPH_REL = os.path.join("graphify-out", "graph.json")
PACKAGE = "graphifyy"          # double-y; other graphify* packages are unrelated (GK15)
TIMEOUT = 1800

# --------------------------------------------------------------------------- ignore rules
#
# DE-DUP, NOT BLANKET IGNORE (GK4). The AI-Forward methodology layer is deployed to two tool
# surfaces, so it is genuinely duplicated - but WHICH copy is canonical depends entirely on
# what kind of repo this is, and getting that backwards guts the graph:
#
#   pack-source repo (ai-forward)   pack/ is the source; .claude/, .github/{instructions,
#                                   prompts,agents} and docs/ai-forward-pack/ are byte-copies
#                                   produced by sync-pack.ps1.
#                                   -> canonical = pack/ ; ignore the four projections.
#
#   CONSUMING repo (a project that  there is NO pack/. The knowledge docs, skills, personas and
#   adopted the pack as a starter)  deployable scripts exist ONLY at .claude/ and
#                                   docs/ai-forward-pack/. Ignoring those would remove every
#                                   standard, skill, persona and script from the graph - so
#                                   `graphify query "what governs our migrations?"` returns
#                                   nothing, which destroys the highest-value use case.
#                                   -> canonical = .claude/ (fuller: 23 personas vs 11, raw
#                                      knowledge) + docs/ai-forward-pack/scripts/ (real
#                                      executable code, not a duplicate of anything here)
#                                   -> ignore only the .github/ mirror surface.
#
# Same intent - graph each thing exactly once - opposite rules. Detect, do not assume.

_COMMON_TAIL = """
# derived data, not authored artifacts
docs/docs-index.js
docs/audit/audit-data.js
docs/health-history.jsonl
docs/_site/
graphify-out/

# third-party and machine-local
node_modules/
docs/.obsidian/
__pycache__/
test-results/
dist/
"""

_HEADER = """\
# .graphifyignore - generated by graphify-setup.py
# See knowledge/code-knowledge-graph.md GK4 (de-dup) and GK5 (rebuild after changing this).
#
# Detected repo kind: {kind}
# Canonical copy of the methodology layer: {canonical}
#
# NOTE (GK5): narrowing this file does NOT take effect on an incremental `graphify update` -
# that is fail-closed and keeps nodes for files that left the corpus. Delete graphify-out/ and
# rebuild ({tool} --build does exactly that).
"""

PACK_SOURCE_RULES = """
# --- this repo IS the pack source: pack/ is canonical, these four are its projections ---
.claude/
.github/instructions/
.github/prompts/
.github/agents/
docs/ai-forward-pack/
web/pack-index.js
"""

CONSUMER_RULES = """
# --- this repo CONSUMES the pack: .claude/ is the canonical surface, .github/ mirrors it ---
# Deliberately NOT ignored, because here they are the only copy that exists:
#   .claude/knowledge, .claude/skills, .claude/agents  - the standards, workflows and personas
#   docs/ai-forward-pack/scripts                       - real executable code this repo runs
#   docs/ai-forward-pack/templates                     - artifact templates
.github/instructions/
.github/prompts/
.github/agents/
"""

PLAIN_RULES = """
# --- no AI-Forward methodology layer detected: nothing to de-duplicate ---
"""


def detect_repo_kind(root: str) -> tuple:
    """Return (kind, canonical, rules). Detect - never assume - which copy is authoritative."""
    if os.path.isfile(os.path.join(root, "pack", "adapters", "INSTALL.md")):
        return ("pack source (this repo builds the pack)", "pack/", PACK_SOURCE_RULES)
    if os.path.isdir(os.path.join(root, "docs", "ai-forward-pack")) or \
       os.path.isdir(os.path.join(root, ".claude", "knowledge")):
        return ("pack consumer (adopted the pack as a starter)",
                ".claude/ + docs/ai-forward-pack/", CONSUMER_RULES)
    return ("plain repo (no AI-Forward layer)", "n/a", PLAIN_RULES)


def ignore_template(root: str, tool: str = "graphify-setup.py") -> tuple:
    kind, canonical, rules = detect_repo_kind(root)
    text = _HEADER.format(kind=kind, canonical=canonical, tool=tool) + rules + _COMMON_TAIL
    return text, kind, canonical


GITIGNORE_RULES = [
    "# Graphify code knowledge graph - a build output, regenerable from source (GK3)",
    "graphify-out/",
]

# Graphify edge tag -> the pack's confidence vocabulary (GK6).
CONFIDENCE_MAP = {"EXTRACTED": "Verified", "INFERRED": "Inferred", "AMBIGUOUS": "Flagged"}


def out(msg: str = "") -> None:
    try:
        print(msg)
    except UnicodeEncodeError:
        enc = getattr(sys.stdout, "encoding", None) or "ascii"
        print(msg.encode(enc, "replace").decode(enc, "replace"))


def write_text_lf(path: str, text: str, dry: bool) -> str:
    if os.path.exists(path):
        try:
            with open(path, encoding="utf-8") as f:
                if f.read() == text:
                    return "unchanged"
        except OSError:
            pass
        action = "would update" if dry else "updated"
    else:
        action = "would create" if dry else "created"
    if not dry:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    return action


def graphify_exe():
    """Resolve the CLI, including uv's tool dir which is often not on PATH in a fresh shell."""
    found = shutil.which("graphify")
    if found:
        return found
    for base in (os.path.expanduser("~/.local/bin"),
                 os.path.join(os.environ.get("APPDATA", ""), "uv", "tools", "bin")):
        for name in ("graphify", "graphify.exe"):
            candidate = os.path.join(base, name)
            if base and os.path.isfile(candidate):
                return candidate
    return None


def run(cmd, cwd, dry, label):
    out(f"    {label}")
    if dry:
        out(f"      (dry run) {' '.join(cmd)}")
        return True
    try:
        res = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                             encoding="utf-8", errors="replace", timeout=TIMEOUT)
    except (OSError, subprocess.SubprocessError) as exc:
        out(f"      failed: {exc}")
        return False
    for line in (res.stdout or "").splitlines()[-8:]:
        out(f"      {line}")
    if res.returncode != 0:
        for line in (res.stderr or "").splitlines()[-6:]:
            out(f"      {line}")
        out(f"      exit {res.returncode}")
    return res.returncode == 0


# --------------------------------------------------------------------------- graphs
def load_code_graph(root):
    path = os.path.join(root, GRAPH_REL)
    if not os.path.exists(path):
        return None, f"{GRAPH_REL} not found - run --build (or `graphify update .`) first"
    try:
        return json.load(open(path, encoding="utf-8")), None
    except (OSError, ValueError) as exc:
        return None, f"could not parse {GRAPH_REL}: {exc}"


def load_docs_graph(root):
    path = os.path.join(root, "docs", "docs-index.js")
    if not os.path.exists(path):
        return None, "docs/docs-index.js not found - run docs-graph.py derive first"
    try:
        with open(path, encoding="utf-8") as f:
            raw = f.read()
        return json.loads(raw[raw.index("{"):raw.rindex("}") + 1]), None
    except (OSError, ValueError) as exc:
        return None, f"could not parse docs-index.js: {exc}"


# A path-ish token inside an artifact: at least one directory segment, then a real extension.
# The extension must contain a letter - otherwise version strings like "WCAG 2.4.11/2.4.13"
# parse as a path and fill the lens with noise, and a noisy lens gets ignored.
PATH_RX = re.compile(r"(?<![\w./-])((?:\.{0,2}[\w.-]+/){1,}[\w.-]*[A-Za-z][\w.-]*\.[A-Za-z][A-Za-z0-9]{0,4})(?![\w/])")
DOCLIKE = {".md", ".markdown"}


def resolve_reference(root: str, artifact_path: str, ref: str):
    """Resolve a referenced path the way a reader would: relative to the artifact first
    (so `../web/index.html` inside docs/index.md works), then relative to the repo root.
    Returns (normalised_repo_relative_path, exists)."""
    art_dir = os.path.dirname(os.path.join(root, artifact_path.replace("/", os.sep)))
    for base in (art_dir, root):
        candidate = os.path.normpath(os.path.join(base, ref.replace("/", os.sep)))
        # stay inside the repo - a traversal escaping the root is not a repo reference
        try:
            rel = os.path.relpath(candidate, root)
        except ValueError:
            continue
        if rel.startswith(".."):
            continue
        if os.path.exists(candidate):
            return rel.replace(os.sep, "/"), True
    # unresolved: report it root-relative for readability
    return os.path.normpath(ref).replace(os.sep, "/"), False


def _lens_staleness(root):
    """Is the committed join lens describing a codebase older than HEAD?

    The code graph itself is a build output and git-ignored, so the only committed evidence
    of when it was built is the commit the lens records about itself. That record is what
    rots - silently, because nothing else looks at it. A lens that quietly describes an
    older codebase is worse than no lens: it is consulted with the same confidence.

    Deliberately narrow: only SOURCE changes count. A documentation-only commit does not
    invalidate a graph of the code, and reporting one would train people to ignore this -
    the same wolf-crying that makes a noisy gate worthless.
    """
    lens = os.path.join(root, "docs", "lenses", "code-doc-join.md")
    try:
        with open(lens, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except OSError:
        return False, "unreadable"

    found = re.search(r"Code graph built at commit `([0-9a-f]{7,40})`", text)
    if not found:
        return True, "the lens does not record the commit it was built at"

    built = found.group(1)
    ok, head = _git(root, "rev-parse", "HEAD")
    if not ok:
        return False, "not a git repository - cannot judge"

    ok, _ = _git(root, "cat-file", "-t", built)
    if not ok:
        return True, f"recorded commit {built[:12]} is not in this repository"

    ok, changed = _git(root, "diff", "--name-only", built, head.strip(), "--", "src", "tests", "app", "lib")
    if not ok:
        return False, "could not compare - cannot judge"

    files = [line for line in changed.splitlines() if line.strip()]
    if files:
        return True, f"STALE - {len(files)} source file(s) changed since {built[:12]}"
    return False, f"current at {built[:12]}"


def _git(root, *args):
    try:
        proc = subprocess.run(
            ["git", "-C", root, *args],
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True,
            encoding="utf-8", errors="replace", timeout=30)
        return proc.returncode == 0, proc.stdout
    except (OSError, subprocess.SubprocessError):
        return False, ""

def join_graphs(root, code, docs, top_n=15):
    """Compute the two gaps between intent and reality (GK11)."""
    nodes = code.get("nodes", [])
    links = code.get("links", [])

    # --- degree over the code graph, and the file each node came from
    degree = Counter()
    for l in links:
        degree[l.get("source")] += 1
        degree[l.get("target")] += 1
    by_id = {n.get("id"): n for n in nodes}
    code_files = {(n.get("source_file") or "").replace("\\", "/") for n in nodes}
    code_files.discard("")

    # --- every path referenced by a docs artifact
    referenced = defaultdict(list)          # path -> [artifact ids]
    unresolved = []                          # (artifact, path) where nothing on disk matches
    for art in docs.get("artifacts", []):
        art_path = art.get("path")
        if not art_path:
            continue
        # Derived output is not a record. The lenses are GENERATED from this graph, and
        # code-doc-join.md lists the very paths reported below - so scanning them makes the
        # lens report ITSELF, and those false positives grow with every run until they drown
        # the real signal. Measured in a consuming repo: 42 of 94 rows were the lens citing
        # its own previous table.
        if art_path.replace(os.sep, "/").startswith("docs/lenses/"):
            continue
        full = os.path.join(root, art_path.replace("/", os.sep))
        try:
            with open(full, encoding="utf-8", errors="replace") as f:
                text = f.read()
        except OSError:
            continue
        for match in set(PATH_RX.findall(text)):
            resolved, exists = resolve_reference(root, art_path, match)
            referenced[resolved].append(art["id"])
            if not exists and resolved not in code_files:
                unresolved.append({"artifact": art["id"], "path": match})

    # --- gap 1: documentation whose referenced code paths do not exist
    #     (skip .md targets: cross-doc links are the docs graph's own concern, checked by
    #      docs-graph.py validate, and double-reporting them here would be noise)
    doc_no_impl = [u for u in unresolved
                   if os.path.splitext(u["path"])[1].lower() not in DOCLIKE]

    # --- gap 2: the riskiest code with no governing documentation
    ranked = [(nid, d) for nid, d in degree.most_common() if nid in by_id]
    risk_no_gov = []
    for nid, deg in ranked:
        node = by_id[nid]
        if node.get("file_type") != "code":
            continue                                     # only code carries this risk
        src = (node.get("source_file") or "").replace("\\", "/")
        governed = [a for p, a in referenced.items()
                    if p == src or (src and p.endswith("/" + os.path.basename(src)))]
        if not governed:
            risk_no_gov.append({
                "symbol": node.get("label"), "degree": deg, "file": src,
                "line": node.get("source_location"), "community": node.get("community_name"),
            })
        if len(risk_no_gov) >= top_n:
            break

    provenance = Counter(l.get("confidence") for l in links)
    return {
        "code_nodes": len(nodes), "code_edges": len(links),
        "code_files": len(code_files),
        "doc_artifacts": len(docs.get("artifacts", [])),
        "provenance": {k: v for k, v in provenance.items() if k},
        "confidence_map": CONFIDENCE_MAP,
        "referenced_paths": len(referenced),
        "doc_without_implementation": sorted(doc_no_impl, key=lambda d: (d["artifact"], d["path"])),
        "risk_without_governance": risk_no_gov,
        "built_at_commit": code.get("built_at_commit"),
    }


def render_join(j) -> str:
    L = []
    add = L.append
    add("# Lens - code/doc join\n")
    add("> **This is a lens, not a record.** It is *derived* at read time from the docs graph\n"
        "> (`docs/docs-index.js`, itself derived from artifact frontmatter) and the code graph\n"
        "> (`graphify-out/graph.json`, derived from source). Both regenerate; neither is edited.\n"
        "> Findings below are **prompts, not failures** (GK11/OB13) - close the gap, or record\n"
        "> why it does not apply.\n")
    add(f"*Code graph: **{j['code_nodes']} nodes**, **{j['code_edges']} edges**, "
        f"{j['code_files']} source files. Docs graph: **{j['doc_artifacts']} artifacts**, "
        f"{j['referenced_paths']} distinct paths referenced.*\n")

    add("## Edge provenance (GK6)\n")
    add("*A citation is not a promotion: an `INFERRED` edge quoted as established is the "
        "Confident Guess with extra steps.*\n")
    add("| graphify tag | pack label | edges |\n|---|---|---|")
    for tag, label in j["confidence_map"].items():
        add(f"| `{tag}` | **{label}** | {j['provenance'].get(tag, 0)} |")

    add("\n## Gap 1 - documentation with no implementation\n")
    add("*An artifact references a code path that exists neither on disk nor in the code graph. "
        "Either it was never written, or it moved and the document now lies.*\n")
    items = j["doc_without_implementation"]
    if items:
        add("| artifact | referenced path |\n|---|---|")
        for i in items:
            add(f"| `{i['artifact']}` | `{i['path']}` |")
    else:
        add("- none - every code path referenced by an artifact resolves")

    add("\n## Gap 2 - risk with no governance\n")
    add("*The most connected code symbols that **no** documentation artifact references. "
        "Change here carries the most blast radius and has the least written intent behind it "
        "(GK10). Run `graphify affected \"<symbol>\"` before touching one.*\n")
    risk = j["risk_without_governance"]
    if risk:
        add("| symbol | degree | file:line | community |\n|---|---|---|---|")
        for r in risk:
            add(f"| `{r['symbol']}` | {r['degree']} | `{r['file']}:{r['line']}` | {r['community']} |")
    else:
        add("- none - every high-degree code symbol is referenced by some artifact")

    add("\n## How to act on this\n")
    add("1. **Gap 1** - fix the reference, or delete the claim. A path that does not resolve is "
        "a documentation defect, and the pack's own rule is that a stale record is a defect "
        "rather than debt (`end-to-end-integrity.md` E17).")
    add("2. **Gap 2** - either write the governing design, or record why the symbol needs none. "
        "A god node with no design is where the next expensive surprise comes from.")
    add("3. **Recurring shapes** - register them as defect *classes* with a control, not as "
        "one-off fixes (`continuous-improvement.md` CI1-CI6).")
    if j.get("built_at_commit"):
        add(f"\n*Code graph built at commit `{j['built_at_commit']}`. Rebuild with "
            "`graphify-setup.py --build` after material code change.*")
    return "\n".join(L) + "\n"


# --------------------------------------------------------------------------- main
def main() -> int:
    ap = argparse.ArgumentParser(description="Stand up the code knowledge graph and join it to the docs graph.")
    ap.add_argument("--root", default=".", help="repository root (default: .)")
    ap.add_argument("--check", action="store_true", help="report state, write nothing (default)")
    ap.add_argument("--install", action="store_true", help="install graphifyy and register the skill")
    ap.add_argument("--platform", default="claude,copilot", help="assistants to register (default: claude,copilot)")
    ap.add_argument("--init", action="store_true", help="write .graphifyignore and the .gitignore rule")
    ap.add_argument("--build", action="store_true", help="full ignore-respecting re-extraction")
    ap.add_argument("--join", action="store_true", help="write docs/lenses/code-doc-join.md")
    ap.add_argument("--top", type=int, default=15, help="ungoverned symbols to report (default 15)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--json", action="store_true", help="machine-readable join output")
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    dry = args.dry_run
    did = False

    if args.install:
        did = True
        out("Installing Graphify (package `graphifyy` - double y; others are unrelated, GK15)")
        if graphify_exe():
            out("    already installed")
        else:
            installer = shutil.which("uv")
            cmd = ([installer, "tool", "install", PACKAGE] if installer
                   else [sys.executable, "-m", "pip", "install", "--user", PACKAGE])
            run(cmd, root, dry, f"install {PACKAGE}")
        exe = graphify_exe()
        if exe and not dry:
            for platform in [p.strip() for p in args.platform.split(",") if p.strip()]:
                run([exe, "install", "--platform", platform], root, dry,
                    f"register the /graphify skill for {platform}")
        elif not exe:
            out("    graphify not on PATH after install - open a new shell, or add "
                "~/.local/bin (uv tool dir) to PATH")

    if args.init:
        did = True
        text, kind, canonical = ignore_template(root)
        out(f"Writing the ignore rules (GK4 - de-dup, not blanket ignore)")
        out(f"    detected: {kind}")
        out(f"    canonical copy: {canonical}")
        out(f"    {write_text_lf(os.path.join(root, '.graphifyignore'), text, dry):>16}  .graphifyignore")
        gi = os.path.join(root, ".gitignore")
        existing = ""
        if os.path.exists(gi):
            with open(gi, encoding="utf-8") as f:
                existing = f.read()
        if "graphify-out/" in existing:
            out(f"    {'unchanged':>16}  .gitignore")
        elif dry:
            out(f"    {'would append':>16}  .gitignore")
        else:
            with io.open(gi, "a", encoding="utf-8", newline="\n") as fh:
                fh.write("\n" + "\n".join(GITIGNORE_RULES) + "\n")
            out(f"    {'appended':>16}  .gitignore")

    if args.build:
        did = True
        exe = graphify_exe()
        if not exe:
            out("error: graphify not found - run --install first")
            return 1
        out("Building the code graph (full re-extraction so ignore rules take effect - GK5)")
        target = os.path.join(root, "graphify-out")
        if os.path.isdir(target):
            out(f"    {'removing' if not dry else 'would remove':>16}  graphify-out/ "
                "(incremental update is fail-closed and would keep stale nodes)")
            if not dry:
                shutil.rmtree(target, ignore_errors=True)
        if not run([exe, "update", "."], root, dry, "graphify update ."):
            return 1

    if args.join:
        did = True
        code, err1 = load_code_graph(root)
        docs, err2 = load_docs_graph(root)
        if err1 or err2:
            out(f"error: {err1 or err2}")
            return 1
        result = join_graphs(root, code, docs, args.top)
        if args.json:
            out(json.dumps(result, indent=2))
        else:
            body = render_join(result)
            dest = os.path.join(root, "docs", "lenses", "code-doc-join.md")
            fm = ("---\n"
                  "id: lens-code-doc-join\n"
                  'title: "Lens - code/doc join"\n'
                  "type: doc\nstatus: accepted\nowner: \"@maintainers\"\n"
                  "tags: [lens, graphify, code-graph, traceability]\n"
                  "links:\n  - { to: lens-graph-structure, rel: relates-to }\n"
                  'review-by: ""\n'
                  "summary: >-\n"
                  "  Derived join between the documentation graph (intent) and the Graphify code\n"
                  "  graph (reality): documentation referencing code that does not exist, and the\n"
                  "  most connected code symbols no artifact governs. A prompt, never a gate.\n"
                  "---\n\n")
            out(body)
            out(f"  {write_text_lf(dest, fm + body, dry)}: docs/lenses/code-doc-join.md")
            out("  Remember to re-run docs-graph.py derive so the lens enters the index (V11).")

    if args.check or not did:
        exe = graphify_exe()
        code, code_err = load_code_graph(root)
        docs, docs_err = load_docs_graph(root)
        findings = []
        out("AI-Forward code knowledge graph (Graphify) - status\n")
        out(f"  {'graphify CLI':<24} {exe or 'NOT INSTALLED - run --install'}")
        if not exe:
            findings.append("graphify not installed")
        ignore_path = os.path.join(root, ".graphifyignore")
        ignore_ok = os.path.exists(ignore_path)
        kind, canonical, _ = detect_repo_kind(root)
        out(f"  {'repo kind':<24} {kind}")
        out(f"  {'canonical copy':<24} {canonical}")
        out(f"  {'.graphifyignore':<24} {'present' if ignore_ok else 'MISSING - run --init (GK4)'}")
        if not ignore_ok:
            findings.append(".graphifyignore missing")
        else:
            # Drift check: the wrong rules for this repo kind are worse than none, because
            # they silently remove the whole methodology layer from a consuming repo's graph.
            with open(ignore_path, encoding="utf-8") as f:
                current = f.read()
            consuming = canonical.startswith(".claude")
            if consuming and re.search(r"(?m)^\.claude/\s*$", current):
                out(f"  {'':<24} WARNING - ignores .claude/ in a CONSUMING repo: the standards,")
                out(f"  {'':<24}           skills and personas exist nowhere else here (GK4)")
                findings.append(".graphifyignore excludes .claude/ in a consuming repo")
            if consuming and re.search(r"(?m)^docs/ai-forward-pack/\s*$", current):
                out(f"  {'':<24} WARNING - ignores docs/ai-forward-pack/ in a CONSUMING repo:")
                out(f"  {'':<24}           that is the only copy of the deployable scripts (GK4)")
                findings.append(".graphifyignore excludes docs/ai-forward-pack/ in a consuming repo")
        if code:
            out(f"  {'code graph':<24} {len(code.get('nodes', []))} nodes, "
                f"{len(code.get('links', []))} edges")
        else:
            out(f"  {'code graph':<24} {code_err}")
            findings.append(code_err)
        out(f"  {'docs graph':<24} "
            f"{str(len(docs.get('artifacts', []))) + ' artifacts' if docs else docs_err}")
        if docs_err:
            findings.append(docs_err)
        joined = os.path.exists(os.path.join(root, "docs", "lenses", "code-doc-join.md"))
        out(f"  {'code/doc join lens':<24} {'present' if joined else 'not generated - run --join'}")
        if joined:
            stale, detail = _lens_staleness(root)
            out(f"  {'lens freshness':<24} {detail}")
            if stale:
                findings.append("code/doc join lens built from source older than HEAD - run --build --join")
        gi = os.path.join(root, ".gitignore")
        ignored = False
        if os.path.exists(gi):
            with open(gi, encoding="utf-8") as f:
                ignored = "graphify-out/" in f.read()
        out(f"  {'graphify-out ignored':<24} {'yes' if ignored else 'NO - run --init (GK3)'}")
        if not ignored:
            findings.append("graphify-out/ not git-ignored")
        out("\n  Graphify is an on-device CODE knowledge graph (graphify.com, Apache 2.0,")
        out("  PyPI `graphifyy`). It complements - never replaces - the docs graph, which")
        out("  remains the record. See knowledge/code-knowledge-graph.md (GK1-GK16).")
        if findings:
            out(f"\n{len(findings)} finding(s): " + "; ".join(findings))
            return 2
        out("\nno findings")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
