"""Wrong-app fixtures for RW1's hidden tests (W1-L 6.2). Each entry is the final reference tree with one substitution (the edit forms of W0 rev 6.6 (g)); `reds` is the exact set of hidden tests it turns red, each by an assertion failure. Test ids are T<turn>-<n>."""

WRONG_APPS = {'wa-nosep': {'reds': ['T1-1', 'T1-2', 'T2-1', 'T2-2', 'T2-4'],
              'edits': [{'file': 'turn-2/humanfriendly/__init__.py', 'old': "'{:,.{}f}'", 'new': "'{:.{}f}'"}]},
 'wa-noneg': {'reds': ['T1-2', 'T2-4'],
              'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                         'old': "    sign = '-' if value < 0 else ''\n",
                         'new': "    sign = ''\n"}]},
 'wa-halfeven': {'reds': ['T1-3', 'T2-2'],
                 'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                            'old': 'rounding=decimal.ROUND_HALF_UP',
                            'new': 'rounding=decimal.ROUND_HALF_EVEN'}]},
 'wa-str': {'reds': ['T1-4'],
            'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                       'old': 'decimal.Decimal(str(amount))',
                       'new': 'decimal.Decimal(0 if isinstance(amount, str) else str(amount))'}]},
 'wa-zero-blank': {'reds': ['T1-5'],
                   'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                              'old': "    sign = '-' if value < 0 else ''\n",
                              'new': '    if value == 0:\n'
                                     "        return ''\n"
                                     "    sign = '-' if value < 0 else ''\n"}]},
 'wa-eur-prefix': {'reds': ['T2-1', 'T2-4'],
                   'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                              'old': "'EUR': ('€', 2, 'after',",
                              'new': "'EUR': ('€', 2, 'before',"}]},
 'wa-jpy-decimals': {'reds': ['T2-2'],
                     'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                                'old': "'JPY': ('¥', 0,",
                                'new': "'JPY': ('¥', 2,"}]},
 'wa-noraise': {'reds': ['T2-3'],
                'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                           'old': '        raise ValueError("Unknown currency code: %r" % (code,))\n',
                           'new': "        return ''\n"}]},
 'wa-eur-neg-prefix': {'reds': ['T2-4'],
                       'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                                  'old': "    return sign + digits + ' ' + symbol\n",
                                  'new': "    return digits + ' ' + symbol + sign\n"}]},
 'wa-nodelegate': {'reds': ['T2-5'],
                   'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                              'old': "    return format_money(amount, 'USD')\n",
                              'new': "    return _format_money(amount, 'USD')\n"}]},
 'wa-dead-delegate': {'reds': ['T2-5'],
                      'edits': [{'file': 'turn-2/humanfriendly/__init__.py',
                                 'old': "    return format_money(amount, 'USD')\n",
                                 'new': "    format_money(amount, 'USD')\n"
                                        "    return _format_money(amount, 'USD')\n"}]}}
